/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class li_cil_oc2_common_inet_DefaultSessionLayer */

#ifndef _Included_li_cil_oc2_common_inet_DefaultSessionLayer
#define _Included_li_cil_oc2_common_inet_DefaultSessionLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     li_cil_oc2_common_inet_DefaultSessionLayer
 * Method:    sendICMP
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_li_cil_oc2_common_inet_DefaultSessionLayer_sendICMP
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
