name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: publish
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt update && sudo apt install clang-19 llvm-19 lld-19

      - name: Build
        run: ./build.sh
        env:
          CLANG: clang-19
          STRIP: llvm-strip-19

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/*"]'
